CREATE DATABASE JOINCLASS

CREATE TABLE JAVA (
PROFESSOR VARCHAR(20) NULL
);

CREATE TABLE NET
(
PROFESSOR VARCHAR(20) NULL
);

INSERT INTO NET 
VALUES ('FABRÍCIO'),('RICARDO'),('ALEXANDRE')

INSERT INTO JAVA 
VALUES ('FABRÍCIO'),('LUCAS'),('DEIVISON')

-- UNINDO AS TABELAS
SELECT * FROM NET
UNION
SELECT * FROM JAVA

-- INNER JOIN
SELECT * FROM JAVA
INNER JOIN NET
ON JAVA.PROFESSOR = NET.PROFESSOR

-- LEFT JOIN
SELECT * FROM JAVA
LEFT JOIN NET
ON
JAVA.PROFESSOR = NET.PROFESSOR
-- LEFT JOIN EXCLUSIVE
SELECT * FROM JAVA
LEFT JOIN NET
ON JAVA.PROFESSOR = NET.PROFESSOR
WHERE NET.PROFESSOR IS NULL

-- RIGHT JOIN
SELECT * FROM JAVA
RIGHT JOIN NET
ON JAVA.PROFESSOR = NET.PROFESSOR
-- EXCLUSIVE RIGHT JOIN 
SELECT * FROM JAVA
RIGHT JOIN  NET
ON JAVA.PROFESSOR = NET.PROFESSOR

--OUTER JOIN
SELECT * FROM JAVA
FULL OUTER JOIN NET
ON JAVA.PROFESSOR = NET.PROFESSOR

-- EXCLUSIVE OUTER JOIN 
SELECT * FROM JAVA
FULL OUTER JOIN NET
ON JAVA.PROFESSOR = NET.PROFESSOR
WHERE JAVA.PROFESSOR IS NULL 
OR
NET.PROFESSOR IS NULL


-- TRIGGERS

create table log 
(
    id integer not null primary key identity,
    acao varchar(10) not null,
    descricao varchar(100),
    quando datetime not null
)

-- --------------------------------------------
CREATE TRIGGER PRIMEIRA_TRIGGER
ON JAVA
-- AFTER OR BEFORE
AFTER DELETE
AS
BEGIN

INSERT INTO LOG VALUES('Exclusão',
						'Um professor de java foi excluído',
						GETDATE())
END

DELETE FROM JAVA WHERE PROFESSOR = 'LUCAS'


-- --------------------------------------------
CREATE TRIGGER SEGUNDA_TRIGGER
ON JAVA
AFTER INSERT
AS
BEGIN
	INSERT INTO LOG VALUES('INSERÇÃO',
							'ADD PROFESSOR JAVA',
							GETDATE());
							PRINT('DADOS INSERIDOS')
							
END

INSERT INTO JAVA VALUES('LUCAS')

-- --------------------------------------------

CREATE TRIGGER TERCEIRA_TRIGGER
ON JAVA
AFTER INSERT
AS
BEGIN
	DECLARE @CONTAGEM INT
	SELECT @CONTAGEM = (SELECT COUNT(PROFESSOR) FROM JAVA)

	PRINT('QUANTIDADE DE PROFESSORES' +
			CONVERT(VARCHAR(10), @CONTAGEM));
	IF @CONTAGEM < 3
		BEGIN
			INSERT INTO LOG VALUES('INSERÇÃO',
								'ADD PROFESSOR JAVA',
								GETDATE());
								PRINT('DADOS INSERIDOS')
			PRINT('INSERIDO COM SUCESSO');
		END
	ELSE
		BEGIN
			ROLLBACK;
			INSERT INTO LOG VALUES('INSERÇÃO',
							'TENTATIVA DE INSERÇÃO MAL SUCEDIDA',
							GETDATE());
			RAISERROR('INVALIDO',14,1);
			RETURN
		END
END

INSERT INTO JAVA VALUES('LUCAS')

-- --------------------------------------------

CREATE TRIGGER QUARTA_TRIGGER
ON JAVA
AFTER UPDATE
AS
BEGIN
	DECLARE @OLD VARCHAR(20)
	DECLARE @NEW VARCHAR(20)

	SELECT @OLD = (SELECT DELETED.PROFESSOR FROM DELETED)
	SELECT @NEW = (SELECT INSERTED.PROFESSOR FROM INSERTED)

	-- SE A INSERÇÃO NAO FOI BEM SUCEDIDA, ESSE TRECHO ENCERRA A TRIGGER
	IF(ROWCOUNT_BIG() = 0)
		RETURN;

	IF @OLD = @NEW
   		BEGIN
       		RAISERROR('SEM ALTERAÇÕES', 14, 1);
       		ROLLBACK TRANSACTION;
       		INSERT INTO LOG VALUES ('ATUALIZAÇÃO', 
           		'TENTATIVA DE UPDATE MAL SUCEDIDA!', GETDATE());
   		END
    ELSE
   		BEGIN
       		INSERT INTO LOG VALUES ('UPD', 
           		'ALTERAÇÃO DO PROF, ' + @OLD + 
           		' PARA ' + @NEW, GETDATE());
   		END
END


SELECT * FROM JAVA
SELECT * FROM LOG
SELECT * FROM NET
