CREATE DATABASE ADONET;

CREATE TABLE PESSOAS
(
ID INTEGER PRIMARY KEY IDENTITY,
NOME VARCHAR(50) NOT NULL,
PROFISSAO VARCHAR(30)
)


CREATE LOGIN ATOS WITH PASSWORD='NEILSANTOS';
CREATE USER USUARIO FROM LOGIN ATOS;

EXEC sp_addrolemember 'DB_DATAREADER', USUARIO;
EXEC sp_addrolemember 'DB_DATAWRITER', USUARIO;


insert into PESSOAS 
VALUES
('neil','Programador'),
('Anderson','Puta')

Select * From PESSOAS
