
-- ------------------[DDL] ------------------
--CREATE
--ALTER
--DROP

-- # [ CREATE ]
CREATE DATABASE AulaAtos;

CREATE TABLE ALUNOS
(
ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
NOME VARCHAR(100) NOT NULL,
CPF VARCHAR(11) NOT NULL,
IDADE INTEGER
);

CREATE TABLE CURSOS
(
ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
NOME VARCHAR(30) NOT NULL,
CARGA_HORARIA INTEGER NOT NULL,
ATIVO BIT DEFAULT 1,
DESCRICAO TEXT
);

CREATE TABLE DISCIPLINAS
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	CARGA_HORARIA INTEGER NOT NULL,
	FK_CURSO INTEGER NOT NULL
	FOREIGN KEY (FK_CURSO) REFERENCES CURSOS(ID)
);

CREATE TABLE MATRICULAS
(
 ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
 FK_ALUNO INTEGER NOT NULL,
 FK_CURSO INTEGER NOT NULL,
 FOREIGN KEY (FK_ALUNO) REFERENCES ALUNOS(ID),
 FOREIGN KEY (FK_CURSO) REFERENCES CURSOS(ID),
);

-- # [ ALTER ]

-- UPDATING SIZE COLUMN NAME
ALTER TABLE ALUNOS
ALTER COLUMN NOME VARCHAR(200);

-- ADDING NEW COLUMNS 
ALTER TABLE ALUNOS
ADD RG VARCHAR(12);

-- REMOVING COLUMNS
ALTER TABLE ALUNOS
DROP COLUMN RG;

-- RENAMING COLUMN
sp_rename 'ALUNOS.NOME','newName','COLUMN';


-- # [ DROP ]
 TABLE ALUNOS -- REMOVE TABLE



-- removing recusively
--DROP CASCADE;





-- ------------------[DML] ------------------
--INSERT
--UPDATE
--DELETE
--SELECT

-- CRUD = CREAT READ UPDATE DELETE

-- # [ INSERT ]
insert into alunos 
values('neil','123123',32);

INSERT INTO ALUNOS(NOME, CPF)
VALUES('NEIL ANGELO','1234567');

-- # [ UPDATE ]

-- Apply to everyone
UPDATE ALUNOS
SET IDADE = 25

-- Apply by ID
UPDATE ALUNOS
SET IDADE = 28
WHERE ID = 2

-- updating age by name
UPDATE ALUNOS
SET IDADE = 32
WHERE NOME = 'NEIL'

-- # [ DELETE ]
DELETE FROM ALUNOS

-- Delete by ID
DELETE FROM ALUNOS
WHERE ID=3

-- Delete case
DELETE FROM ALUNOS
WHERE IDADE = NULL --Or IDADE IS NULL or even IS NOT NULL


-- # [ SELECT ]
SELECT * FROM ALUNOS

SELECT * FROM ALUNOS
where nome != ''
order by nome

SELECT * FROM ALUNOS
where nome != ''
order by nome ASC

SELECT * FROM ALUNOS
where nome != ''
order by 2 DESC



