CREATE TABLE ALUNOS
(
ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
NOME VARCHAR(100) NOT NULL,
CPF VARCHAR(11) NOT NULL,
IDADE INTEGER
);

DROP TABLE ALUNOS -- REMOVE TABLE

-- ADDING NEW COLUMNS 
ALTER TABLE ALUNOS
ADD RG VARCHAR(12);

-- REMOVING COLUMNS
ALTER TABLE ALUNOS
DROP COLUMN IDADE;

-- UPDATING SIZE COLUMN NAME
ALTER TABLE ALUNOS
ALTER COLUMN NOME VARCHAR(200);