
CREATE TABLE CATEGORIA
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	TIPO_CATEGORIA VARCHAR(30)
);

CREATE TABLE EDITORA
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(50)
);

CREATE TABLE AUTOR
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(100) NOT NULL,
	NACIONALIDADE VARCHAR(2) NOT NULL
);

CREATE TABLE LIVRO
(
	ISBN VARCHAR(13) NOT NULL PRIMARY KEY,
	TITULO VARCHAR(50),
	ANO_PUBLICACAO INTEGER,
	FK_EDITORA INTEGER NOT NULL,
	FK_CATEGORIA INTEGER NOT NULL,
	FOREIGN KEY (FK_EDITORA) REFERENCES EDITORA(ID),
	FOREIGN KEY (FK_CATEGORIA) REFERENCES CATEGORIA(ID),

);

CREATE TABLE LIVROAUTOR
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	FK_LIVRO VARCHAR(13) NOT NULL,
	FK_AUTOR INTEGER NOT NULL,
	FOREIGN KEY (FK_LIVRO) REFERENCES LIVRO(ISBN),
	FOREIGN KEY (FK_AUTOR) REFERENCES AUTOR(ID),
);